apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-{{ .Values.app_name }}
  labels:
    app: roboshop-{{ .Values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roboshop-{{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: roboshop-{{ .Values.app_name }}
      {{- $prometheusEnabled := true -}}
      {{- if and .Values.prometheus (kindIs "bool" .Values.prometheus.enabled) -}}
      {{- $prometheusEnabled = .Values.prometheus.enabled -}}
      {{- end -}}
      {{- if $prometheusEnabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.app_port }}"
        prometheus.io/path: {{ .Values.prometheus.path | default "/metrics" | quote }}
      {{- end }}
    spec:
      containers:
      - name: roboshop-{{ .Values.app_name }}
        image: raghudevopsb89.azurecr.io/roboshop-{{ .Values.app_name }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: roboshop-{{ .Values.app_name }}
