---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ex1-allow
  namespace: example1
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/example2/sa/debug"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["*"]

