{{ if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: roboshop-{{ .Values.app_name }}-redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{ end }}
