apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: roboshop-{{ .Values.app_name }}
  annotations:
    meta.helm.sh/release-name: shipping
    meta.helm.sh/release-namespace: roboshop
    prometheus-operator-validated: "true"
  labels:
    app.kubernetes.io/managed-by: Helm
    release: pstack
spec:
  groups:
  - name: roboshop-{{ .Values.app_name }}
    rules:
    - alert: HttpResponseTimeHigh
      expr: http_server_requests_seconds_max > 1
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "HttpResponseTimeHigh for {{`{{ $labels.service }}`}}"
        description: "There is a high response time been observed for this application"
{{ if eq  .Values.app_name "frontend" }}
    - alert: HttpFailuresFromTraefik
      expr: traefik_service_requests_total{service="roboshop-roboshop-frontend-80@kubernetes",code =~ "499|502"} > 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "HttpFailures for {{`{{ $labels.service }}`}}"
        description: "HTTP Failures reported"
{{ end }}

