apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: roboshop-{{ .Values.app_name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
spec:
  provider:
    azurekv:
      tenantId: "229f3fa3-57f3-4e2c-852f-24b7bf512640"
      vaultUrl: "https://roboshopb89-{{ .Values.app_name }}.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: roboshop-{{ .Values.app_name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: roboshop-{{ .Values.app_name }}
  target:
    name: roboshop-{{ .Values.app_name }}
    creationPolicy: Owner

  data:
{{- range .Values.secrets_keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ . | replace "_" "-" }}
{{- end }}


